# Generated by Django 3.1.2 on 2020-12-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201216_1839'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserEncoding',
            new_name='FaceEncoding',
        ),
    ]
