# Generated by Django 3.1.2 on 2020-12-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201216_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faceencoding',
            name='user',
            field=models.IntegerField(),
        ),
    ]
