# Generated by Django 3.1.2 on 2021-01-02 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210101_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 2, 4, 16, 49, 761563, tzinfo=utc), null=True),
        ),
    ]
