# Generated by Django 3.1.2 on 2021-01-05 02:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20210104_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 2, 2, 53, 534176, tzinfo=utc), null=True),
        ),
    ]
