# Generated by Django 3.1.2 on 2021-01-05 02:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20210104_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 5, 2, 11, 26, 975720, tzinfo=utc), null=True),
        ),
    ]
