# Generated by Django 3.1.2 on 2021-01-06 00:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210104_2038'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagecomponent',
            name='componentType',
            field=models.CharField(default='Image', max_length=20),
        ),
        migrations.AddField(
            model_name='textcomponent',
            name='componentType',
            field=models.CharField(default='Text', max_length=20),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='data',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 6, 0, 57, 29, 591176, tzinfo=utc), null=True),
        ),
    ]
