# Generated by Django 3.1.2 on 2021-01-07 06:44

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20210105_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 7, 6, 44, 29, 493225, tzinfo=utc), null=True),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
