# Generated by Django 3.1.2 on 2021-01-21 01:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20210119_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecomponent',
            name='caption',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='textcomponent',
            name='data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 21, 1, 25, 18, 744166, tzinfo=utc), null=True),
        ),
    ]
