# Generated by Django 3.1.2 on 2021-01-23 02:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20210120_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagecomponent',
            name='imageID',
        ),
        migrations.AddField(
            model_name='imagecomponent',
            name='imgURL',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='vaultentry',
            name='last_edited',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2021, 1, 23, 2, 38, 2, 196084, tzinfo=utc), null=True),
        ),
    ]
